import type { User, Food, Meal, Recipe, DailyStats } from '@/types';

// Mock current user
export const mockUser: User = {
  id: '1',
  email: 'user@example.com',
  name: 'דני כהן',
  dailyCalorieGoal: 2000,
  proteinGoal: 150,
  carbsGoal: 200,
  fatGoal: 70,
  fiberGoal: 30,
};

// Mock foods database
export const mockFoods: Food[] = [
  {
    id: '1',
    nameHe: 'ביצה',
    nameEn: 'Egg',
    calories: 70,
    protein: 6,
    carbs: 0.5,
    fat: 5,
    fiber: 0,
    sugar: 0.5,
    sodium: 70,
    servingSize: 50,
    servingUnit: 'g',
    source: 'usda',
    verified: true,
  },
  {
    id: '2',
    nameHe: 'לחם מלא',
    nameEn: 'Whole Wheat Bread',
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    fiber: 7,
    sugar: 6,
    sodium: 400,
    servingSize: 100,
    servingUnit: 'g',
    source: 'usda',
    verified: true,
  },
  {
    id: '3',
    nameHe: 'אבוקדו',
    nameEn: 'Avocado',
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
    sugar: 0.7,
    sodium: 7,
    servingSize: 100,
    servingUnit: 'g',
    source: 'usda',
    verified: true,
  },
  {
    id: '4',
    nameHe: 'עוף חזה',
    nameEn: 'Chicken Breast',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    servingSize: 100,
    servingUnit: 'g',
    source: 'usda',
    verified: true,
  },
  {
    id: '5',
    nameHe: 'אורז',
    nameEn: 'Rice',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 1,
    servingSize: 100,
    servingUnit: 'g',
    source: 'usda',
    verified: true,
  },
  {
    id: '6',
    nameHe: 'בננה',
    nameEn: 'Banana',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12,
    sodium: 1,
    servingSize: 100,
    servingUnit: 'g',
    source: 'usda',
    verified: true,
  },
  {
    id: '7',
    nameHe: 'יוגורט יווני',
    nameEn: 'Greek Yogurt',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugar: 3.2,
    sodium: 36,
    servingSize: 100,
    servingUnit: 'g',
    source: 'usda',
    verified: true,
  },
  {
    id: '8',
    nameHe: 'שקדים',
    nameEn: 'Almonds',
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
    sugar: 4.4,
    sodium: 1,
    servingSize: 100,
    servingUnit: 'g',
    source: 'usda',
    verified: true,
  },
];

// Mock meals for today
export const mockMeals: Meal[] = [
  {
    id: '1',
    userId: '1',
    name: 'ארוחת בוקר',
    mealType: 'breakfast',
    timestamp: new Date(new Date().setHours(8, 0, 0, 0)),
    parsedText: '2 ביצים וטוסט עם אבוקדו',
    items: [
      {
        id: '1-1',
        food: mockFoods[0], // ביצה
        quantity: 100,
        unit: 'g',
        calories: 140,
        protein: 12,
        carbs: 1,
        fat: 10,
      },
      {
        id: '1-2',
        food: mockFoods[1], // לחם
        quantity: 60,
        unit: 'g',
        calories: 148,
        protein: 8,
        carbs: 25,
        fat: 2,
      },
      {
        id: '1-3',
        food: mockFoods[2], // אבוקדו
        quantity: 50,
        unit: 'g',
        calories: 80,
        protein: 1,
        carbs: 4.5,
        fat: 7.5,
      },
    ],
    totalCalories: 368,
    totalProtein: 21,
    totalCarbs: 30.5,
    totalFat: 19.5,
    totalFiber: 5.5,
  },
  {
    id: '2',
    userId: '1',
    name: 'ארוחת צהריים',
    mealType: 'lunch',
    timestamp: new Date(new Date().setHours(13, 30, 0, 0)),
    parsedText: 'עוף עם אורז וסלט',
    items: [
      {
        id: '2-1',
        food: mockFoods[3], // עוף
        quantity: 150,
        unit: 'g',
        calories: 248,
        protein: 46.5,
        carbs: 0,
        fat: 5.4,
      },
      {
        id: '2-2',
        food: mockFoods[4], // אורז
        quantity: 200,
        unit: 'g',
        calories: 260,
        protein: 5.4,
        carbs: 56,
        fat: 0.6,
      },
    ],
    totalCalories: 508,
    totalProtein: 51.9,
    totalCarbs: 56,
    totalFat: 6,
    totalFiber: 0.8,
  },
];

// Mock recipes
export const mockRecipes: Recipe[] = [
  {
    id: '1',
    userId: '1',
    nameHe: 'שייק חלבון בננה',
    nameEn: 'Banana Protein Shake',
    description: 'שייק חלבון טעים ומזין לאחר אימון',
    category: 'drink',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    servings: 1,
    instructions: '1. קלפו בננה\n2. הוסיפו יוגורט יווני\n3. הוסיפו שקדים\n4. בלנדר עד חלק\n5. תהנו!',
    ingredients: [
      {
        id: 'ri-1',
        food: mockFoods[5], // בננה
        quantity: 100,
        unit: 'g',
        notes: 'קלופה',
      },
      {
        id: 'ri-2',
        food: mockFoods[6], // יוגורט
        quantity: 200,
        unit: 'g',
      },
      {
        id: 'ri-3',
        food: mockFoods[7], // שקדים
        quantity: 20,
        unit: 'g',
        notes: 'טחונים',
      },
    ],
    totalCalories: 324,
    totalProtein: 25.2,
    totalCarbs: 37.2,
    totalFat: 10.7,
    totalFiber: 5,
    caloriesPerServing: 324,
    proteinPerServing: 25.2,
    tags: ['חלבון', 'בריא', 'מהיר'],
    isPublic: false,
  },
  {
    id: '2',
    userId: '1',
    nameHe: 'טוסט אבוקדו וביצה',
    nameEn: 'Avocado Toast with Egg',
    description: 'ארוחת בוקר קלאסית ומזינה',
    category: 'breakfast',
    difficulty: 'easy',
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 1,
    instructions: '1. קלו את הלחם\n2. טגנו ביצה\n3. מרחו אבוקדו על הטוסט\n4. הוסיפו את הביצה מעל\n5. תבלו במלח ופלפל',
    ingredients: [
      {
        id: 'ri-4',
        food: mockFoods[1], // לחם
        quantity: 60,
        unit: 'g',
      },
      {
        id: 'ri-5',
        food: mockFoods[2], // אבוקדו
        quantity: 50,
        unit: 'g',
        notes: 'מרוסק',
      },
      {
        id: 'ri-6',
        food: mockFoods[0], // ביצה
        quantity: 50,
        unit: 'g',
      },
    ],
    totalCalories: 298,
    totalProtein: 14,
    totalCarbs: 30,
    totalFat: 10.4,
    totalFiber: 7.5,
    caloriesPerServing: 298,
    proteinPerServing: 14,
    tags: ['בוקר', 'בריא', 'מהיר'],
    isPublic: true,
  },
];

// Mock daily stats
export const mockDailyStats: DailyStats = {
  date: new Date(),
  calories: mockMeals.reduce((sum, meal) => sum + meal.totalCalories, 0),
  protein: mockMeals.reduce((sum, meal) => sum + meal.totalProtein, 0),
  carbs: mockMeals.reduce((sum, meal) => sum + meal.totalCarbs, 0),
  fat: mockMeals.reduce((sum, meal) => sum + meal.totalFat, 0),
  fiber: mockMeals.reduce((sum, meal) => sum + meal.totalFiber, 0),
  meals: mockMeals,
};
